import Script from "next/script";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import LayoutCompo from "./LayoutCompo";


export const metadata = {
  title: "vogue wardrobe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<head>

  <meta name="google-site-verification" content="_Xk-yc7PZtnKP_8DqajovbHt7dw8vsNFy359VX29x1U" />
        
        {/* GTM */}
        <Script id="gtm-script" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});
          var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
          j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id=GTM-TFPGGQL5'+dl;
          f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-TFPGGQL5');`}
        </Script>

        {/* Meta Pixel */}
        <Script id="fb-pixel" strategy="afterInteractive">
          {`!function(f,b,e,v,n,t,s)
          {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
          n.callMethod.apply(n,arguments):n.queue.push(arguments)};
          if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
          n.queue=[];t=b.createElement(e);t.async=!0;
          t.src=v;s=b.getElementsByTagName(e)[0];
          s.parentNode.insertBefore(t,s)}(window, document,'script',
          'https://connect.facebook.net/en_US/fbevents.js');
          fbq('init', '2160667241436809');
          fbq('track', 'PageView');`}
        </Script>

</head>
      
      <body >
        <noscript>
          <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TFPGGQL5"
          height="0" width="0" style={{display:"none", visibility:"hidden"}}></iframe>
        </noscript>
        <LayoutCompo >

          {children}
        </LayoutCompo>
      </body>
    </html>
  );
}
