import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import LayoutCompo from "./LayoutCompo";


export const metadata = {
  title: "vogue wardrobe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      
      <body >
        <LayoutCompo >

          {children}
        </LayoutCompo>
      </body>
    </html>
  );
}
